### ISSUE TITLE
Cache python dependencies in github actions

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-2022#25]
It takes several minutes to install python dependencies in github actions, it might be useful to configure caching of some kind: https://github.com/actions/setup-python

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v3
  with:
    python-version: '3.9'
    cache: 'pip'
- run: pip install -r requirements.txt
```
